# Generated by Django 4.2.17 on 2025-03-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Batch Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity of Product in Batch')),
                ('manufacturing_date', models.DateField(verbose_name='Batch Manufacturing Date')),
                ('expiry_date', models.DateField(verbose_name='Batch Expiry Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Batch Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Batch Creation Date')),
            ],
            options={
                'verbose_name': 'Product Batch',
                'verbose_name_plural': 'Product Batches',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturers Name')),
                ('quantity', models.IntegerField(verbose_name='Product Quantity')),
                ('category', models.CharField(max_length=100, verbose_name='Product Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('maufacturing_date', models.DateField(verbose_name='Product Manufacturing Date')),
                ('expiry_date', models.DateField(verbose_name='Product Expiry Date')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='Product Description')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.batch', verbose_name='Product Batch')),
            ],
        ),
    ]
