# Generated by Django 4.2.17 on 2025-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('expired', 'EXPIRED'), ('near-expired', 'NEAR EXPIRY')], default='active', max_length=20),
        ),
    ]
